import weave

from core.github_client import post_review
from core.state import ReviewState

# claude-sonnet-4-6 pricing ($/million tokens) — used as conservative upper bound
_PRICE_IN = 3.00
_PRICE_OUT = 15.00


def _build_summary(state: ReviewState) -> str:
    counts = {"HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for f in state["findings"]:
        counts[f.get("severity", "LOW")] += 1

    status = "PASSED" if state["test_passed"] else "FAILED"
    iterations = state["iteration"]
    patches = len(state["patches"])

    in_tok = state.get("input_tokens", 0)
    out_tok = state.get("output_tokens", 0)
    cost = (in_tok / 1_000_000 * _PRICE_IN) + (out_tok / 1_000_000 * _PRICE_OUT)

    return (
        "## AutoReview Agent — Summary\n\n"
        f"| | |\n|---|---|\n"
        f"| Findings | HIGH: {counts['HIGH']} · MEDIUM: {counts['MEDIUM']} · LOW: {counts['LOW']} |\n"
        f"| Patches generated | {patches} |\n"
        f"| Tests | {status} (after {iterations} iteration(s)) |\n"
        f"| Tokens | {in_tok:,} in · {out_tok:,} out |\n"
        f"| Est. cost | ${cost:.4f} |\n\n"
        "_Generated by [AutoReview Agent](https://github.com)_"
    )


@weave.op()
def publisher_node(state: ReviewState) -> dict:
    comments = [
        {
            "path": f["file"],
            "line": f["line"],
            "body": (
                f"**[{f['severity']}]** {f['description']} "
                f"(confidence: {f.get('confidence', 0):.0%})"
            ),
        }
        for f in state["findings"]
        if f.get("line")
    ]

    body = _build_summary(state)

    if state["repo_slug"] and state["pr_number"]:
        post_review(state["repo_slug"], state["pr_number"], body, comments)

    return {}
