from core.github_client import post_review
from core.state import ReviewState


def _build_summary(state: ReviewState) -> str:
    counts = {"HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for f in state["findings"]:
        counts[f.get("severity", "LOW")] += 1

    status = "PASSED" if state["test_passed"] else "FAILED"
    iterations = state["iteration"]
    patches = len(state["patches"])

    return (
        "## AutoReview Agent — Summary\n\n"
        f"| | |\n|---|---|\n"
        f"| Findings | HIGH: {counts['HIGH']} · MEDIUM: {counts['MEDIUM']} · LOW: {counts['LOW']} |\n"
        f"| Patches generated | {patches} |\n"
        f"| Tests | {status} (after {iterations} iteration(s)) |\n\n"
        "_Generated by [AutoReview Agent](https://github.com)_"
    )


def publisher_node(state: ReviewState) -> dict:
    # TODO (S4): add cost from W&B Weave trace to summary
    comments = [
        {
            "path": f["file"],
            "line": f["line"],
            "body": (
                f"**[{f['severity']}]** {f['description']} "
                f"(confidence: {f.get('confidence', 0):.0%})"
            ),
        }
        for f in state["findings"]
        if f.get("line")
    ]

    body = _build_summary(state)

    if state["repo_slug"] and state["pr_number"]:
        post_review(state["repo_slug"], state["pr_number"], body, comments)

    return {}
